package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Проверка заполнения формы обратной связи")
    void generatedTest() {
        step("Open \"https://rockits.ru/\"", () -> {
            step("// todo: just add selenium action");
        });

        step("click button \"Связаться\"", () -> {
            step("// todo: just add selenium action");
        });

        step("set email \"konstantingrandf@gmail.com\"", () -> {
            step("// todo: just add selenium action");
        });

        step("set username \"Константин\"", () -> {
            step("// todo: just add selenium action");
        });

        step("set usercompany \"Самозанятый\"", () -> {
            step("// todo: just add selenium action");
        });

        step("set usernumber \"89514955775\"", () -> {
            step("// todo: just add selenium action");
        });

        step("set text \"Благодарю за потраченное время и обратную связь!\"", () -> {
            step("// todo: just add selenium action");
        });

        step("submit form", () -> {
            step("// todo: just add selenium action");
        });

        step("Verify successful filled form", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://rockits.ru/'", () ->
            open("https://rockits.ru/"));

        step("Page title should have text 'Hi, Rockits! - Кадровое агентство по подбору IT-специалистов'", () -> {
            String expectedTitle = "Hi, Rockits! - Кадровое агентство по подбору IT-специалистов";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://rockits.ru/'", () ->
            open("https://rockits.ru/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}